### ISSUE TITLE
Possible to embed Google Drive videos?

### ISSUE THREAD

**Issue by shahadatksr** [nathancy/jekyll-embed-video#1]
As the tittle says,I want to know if it is possible to embed Google drive videos.If yes then how to do it without giving away the url of the video.

**Comment by nathancy** [comment]
Hmmm interesting. Haven't thought about embedding Google drive videos. I'll
look into it. I'm guessing its possible since its probably just putting an
iframe element in. Thanks

**Comment by shahadatksr** [comment]
Thanks for the quick reply.Will be looking forward to it.

**Comment by nathancy** [comment]
I've added the functionality in. Look at the README.md for steps to embed a Google drive video. Take a look at the demo link to see the result.
